const OVER_TIME_ERROR = "OVER_TIME_ERROR";
const TIME_DIFFERENCE_ERROR = "TIME_DIFFERENCE_ERROR";
const DATE_DIFFERENCE_ERROR = "DATE_DIFFERENCE_ERROR";
const PAST_TIME_ERROR = "PAST_TIME_ERROR";
const OK = "OK";
const PARAMETER_ERROR_MESSAGE = "PARAMETER IS EMPTY";
const VALIDATION_ERROR_MESSAGE = "VALIDATION CHECK FAIL";
const OVER_TIME_ERROR_MESSAGE = "END TIME SHOULD BE LATER THAN START TIME";
const TIME_DIFFERENCE_ERROR_MESSAGE = "END TIME SHOULD BE MORE THAN 24 HOURS LATER THAN START TIME";
const DATE_DIFFERENCE_ERROR_MESSAGE = "SHORT TERM RENTAL SHOULD NOT BE MORE THAN 14 DAYS";
const PAST_TIME_ERROR_MESSAGE = "START TIME AND END TIME SHOULD BE LATER THAN NOW";
const TYPE_ERROR_MESSAGE = "PARAMETER DOES NOT MATCH ITS TYPE";
const LENGTH_REQUIRED = 411;
const PRECONDITION_FAILED = 412;

module.exports = { 
    OVER_TIME_ERROR, 
    TIME_DIFFERENCE_ERROR,
    DATE_DIFFERENCE_ERROR,
    PAST_TIME_ERROR, 
    OK, 
    PARAMETER_ERROR_MESSAGE, 
    VALIDATION_ERROR_MESSAGE, 
    OVER_TIME_ERROR_MESSAGE, 
    TIME_DIFFERENCE_ERROR_MESSAGE,
    DATE_DIFFERENCE_ERROR_MESSAGE, 
    PAST_TIME_ERROR_MESSAGE, 
    TYPE_ERROR_MESSAGE,
    LENGTH_REQUIRED,
    PRECONDITION_FAILED
};
