const TOTAL_HOURS_OF_1DAY = 24;
const TOTAL_MINS_OF_1HOUR = 60;
const TOTAL_SECONDS_OF_1MIN = 60;
const MINIMUM_HOURS_OF_RENT = 24;
const MAXIMUM_DAYS_OF_RENT = 14;

module.exports = { 
    TOTAL_HOURS_OF_1DAY, 
    TOTAL_MINS_OF_1HOUR,
    TOTAL_SECONDS_OF_1MIN,
    MINIMUM_HOURS_OF_RENT,
    MAXIMUM_DAYS_OF_RENT
};
